package Views;

import DatabaseServices.DBConnect;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author GOVINDA SHARMA
 */
public class CustomerRegistration extends javax.swing.JFrame {

    /**
     * Creates new form CustomerRegistration
     */
    public CustomerRegistration() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtValidTill = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        loginCustomer = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtValidFrom = new javax.swing.JTextField();
        txtCardNum = new javax.swing.JTextField();
        txtCVV = new javax.swing.JTextField();
        registerCustomer = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        txtAptNum = new javax.swing.JTextField();
        txtStName = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        txtProvince = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 46, 30));
        setBounds(new java.awt.Rectangle(350, 100, 0, 0));
        setForeground(new java.awt.Color(0, 46, 30));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setPreferredSize(new java.awt.Dimension(600, 530));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 184, 163));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 530));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(600, 145));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 140));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Banner.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel14.setPreferredSize(new java.awt.Dimension(600, 145));
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 144));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 144));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(225, 90, 71));
        jLabel2.setText("Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 80, 20));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(225, 90, 71));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 80, 20));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(225, 90, 71));
        jLabel6.setText("Valid till");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 90, 20));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(225, 90, 71));
        jLabel7.setText("Shipping Addess");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, 20));

        jLabel9.setBackground(new java.awt.Color(225, 90, 71));
        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(225, 90, 71));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SIGN UP");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 145, 400, 25));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(225, 90, 71));
        jLabel11.setText("Card #");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 80, 20));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(225, 90, 71));
        jLabel12.setText("Valid From");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 80, 20));

        txtValidTill.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtValidTill.setForeground(new java.awt.Color(225, 90, 71));
        jPanel1.add(txtValidTill, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 150, -1));

        jPanel3.setBackground(new java.awt.Color(225, 90, 71));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginCustomer.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        loginCustomer.setForeground(new java.awt.Color(255, 255, 255));
        loginCustomer.setText("Already registered? Login here...");
        loginCustomer.setContentAreaFilled(false);
        loginCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginCustomerActionPerformed(evt);
            }
        });
        jPanel3.add(loginCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 0, -1, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 461, 600, 40));

        txtID.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtID.setForeground(new java.awt.Color(225, 90, 71));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 150, -1));

        txtFullName.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtFullName.setForeground(new java.awt.Color(225, 90, 71));
        jPanel1.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 150, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(225, 90, 71));
        jLabel3.setText("Full Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, 20));

        jPanel4.setBackground(new java.awt.Color(225, 90, 71));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 165, 600, 1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(225, 90, 71));
        jLabel5.setText("Customer ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 80, 20));

        txtPassword.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(225, 90, 71));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 150, -1));

        jLabel15.setBackground(new java.awt.Color(225, 90, 71));
        jLabel15.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(225, 90, 71));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("PAYMENT INFO");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 400, 25));

        jPanel5.setBackground(new java.awt.Color(225, 90, 71));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 600, 1));

        jLabel16.setBackground(new java.awt.Color(225, 90, 71));
        jLabel16.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(225, 90, 71));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("SHIPPING & CONTACT INFO");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 400, 25));

        jPanel6.setBackground(new java.awt.Color(225, 90, 71));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 600, 1));

        txtConfirmPassword.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtConfirmPassword.setForeground(new java.awt.Color(225, 90, 71));
        txtConfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmPasswordFocusLost(evt);
            }
        });
        jPanel1.add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 150, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(225, 90, 71));
        jLabel8.setText("Confirm Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, 20));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(225, 90, 71));
        jLabel10.setText("Contact");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 80, 20));

        txtContact.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtContact.setForeground(new java.awt.Color(225, 90, 71));
        jPanel1.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 150, -1));

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(225, 90, 71));
        jLabel17.setText("CVV");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 100, 20));

        txtValidFrom.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtValidFrom.setForeground(new java.awt.Color(225, 90, 71));
        jPanel1.add(txtValidFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 150, -1));

        txtCardNum.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtCardNum.setForeground(new java.awt.Color(225, 90, 71));
        jPanel1.add(txtCardNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 150, -1));

        txtCVV.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtCVV.setForeground(new java.awt.Color(225, 90, 71));
        jPanel1.add(txtCVV, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 150, -1));

        registerCustomer.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        registerCustomer.setForeground(new java.awt.Color(225, 90, 71));
        registerCustomer.setText("SAVE");
        registerCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(registerCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 100, 30));

        txtEmail.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(225, 90, 71));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 150, -1));

        txtAptNum.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtAptNum.setForeground(new java.awt.Color(225, 90, 71));
        txtAptNum.setText("Apt#");
        txtAptNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAptNumFocusGained(evt);
            }
        });
        jPanel1.add(txtAptNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 45, -1));

        txtStName.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtStName.setForeground(new java.awt.Color(225, 90, 71));
        txtStName.setText("Street Name");
        txtStName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStNameFocusGained(evt);
            }
        });
        jPanel1.add(txtStName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 100, -1));

        txtCountry.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtCountry.setForeground(new java.awt.Color(225, 90, 71));
        txtCountry.setText("Country");
        txtCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountryActionPerformed(evt);
            }
        });
        txtCountry.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCountryFocusGained(evt);
            }
        });
        jPanel1.add(txtCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 300, 75, -1));

        txtProvince.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        txtProvince.setForeground(new java.awt.Color(225, 90, 71));
        txtProvince.setText("Province");
        txtProvince.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProvinceFocusGained(evt);
            }
        });
        jPanel1.add(txtProvince, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 501));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void registerCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerCustomerActionPerformed
        // TODO add your handling code here:
        System.out.println("Register clicked");
        System.out.println("Register clicked");
        if(txtID.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter Admin ID...");
        } else if(txtPassword.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter Password...");
        } else if(!txtConfirmPassword.getText().equals(txtPassword.getText())){
            JOptionPane.showMessageDialog(this, "Password and Confirm Password do not match...");
        } else if(txtFullName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter Full Name...");
        } else if(txtEmail.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter Email...");
        } else if(txtEmail.getText().indexOf("@") == -1 || txtEmail.getText().indexOf(".") == -1){
            JOptionPane.showMessageDialog(this,"Entered email is incorrect...");
        } else if(txtContact.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter Contact...");
        } else if(txtAptNum.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter Apartment Number...");
        } else if(txtStName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter Street Name...");
        } else if(txtProvince.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter Province...");
        } else if(txtCountry.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter Country...");
        } else if(txtCardNum.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter Card Number...");
        } else if(txtCVV.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter CVV Number...");
        } else if(txtValidFrom.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter Date Card Valid From...");
        } else if(txtValidTill.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter Date Card Valid Till...");
        } else {
            Statement statement = DBConnect.getStatement();
            String query = "insert into customer(ID, password, name, email, contact, aptnumber, streetname, province, country, cardnumber, cvv, issuedate, expirydate) values('"+txtID.getText()+"','"+txtPassword.getText()+"','"+txtFullName.getText()+"','"+txtEmail.getText()+"','"+txtContact.getText()+"','"+txtAptNum.getText()+"','"+txtStName.getText()+"','"+txtProvince.getText()+"','"+txtCountry.getText()+"','"+txtCardNum.getText()+"','"+txtCVV.getText()+"','"+txtValidFrom.getText()+"','"+txtValidTill.getText()+"')";
            try {
                if (!statement.execute(query)) {
                    JOptionPane.showMessageDialog(this,"CUSTOMER REGISTERED SUCCESSFULLY...!!!");
                } else {
                    JOptionPane.showMessageDialog(this,"OOPS...!!! SOMETHING WENT WRONG...!!!");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_registerCustomerActionPerformed

    private void loginCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginCustomerActionPerformed
        // TODO add your handling code here:
        CustomerLogin cstmrLgn = new CustomerLogin();
        cstmrLgn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginCustomerActionPerformed

    private void txtCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountryActionPerformed

    private void txtAptNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAptNumFocusGained
        // TODO add your handling code here:
        txtAptNum.setText("");
    }//GEN-LAST:event_txtAptNumFocusGained

    private void txtStNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStNameFocusGained
        // TODO add your handling code here:
        txtStName.setText("");
    }//GEN-LAST:event_txtStNameFocusGained

    private void txtProvinceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProvinceFocusGained
        // TODO add your handling code here:
        txtProvince.setText("");
    }//GEN-LAST:event_txtProvinceFocusGained

    private void txtCountryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCountryFocusGained
        // TODO add your handling code here:
        txtCountry.setText("");
    }//GEN-LAST:event_txtCountryFocusGained

    private void txtConfirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmPasswordFocusLost
        // TODO add your handling code here:
        if(!txtConfirmPassword.getText().equals(txtPassword.getText())){
            JOptionPane.showMessageDialog(this, "Password and Confirm Password do not match...");
        }
    }//GEN-LAST:event_txtConfirmPasswordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerRegistration().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton loginCustomer;
    private javax.swing.JButton registerCustomer;
    private javax.swing.JTextField txtAptNum;
    private javax.swing.JTextField txtCVV;
    private javax.swing.JTextField txtCardNum;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtID;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtProvince;
    private javax.swing.JTextField txtStName;
    private javax.swing.JTextField txtValidFrom;
    private javax.swing.JTextField txtValidTill;
    // End of variables declaration//GEN-END:variables
}
